version: '3.7'

services:
  spring-app:
      container_name: spring-app
      image: springApp:0.1.0
      build: 
        context: . 
        target: develop
      ports:
        - 9887:8080
      tty: true
      environment:
        - EVAL=manuel
      working_dir: /test
#      volumes:
#        - ./:/camel

#volumes:
#  local:
    
    