    apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: exlipse-mosquitto:1.6.2
          ports:
            - containerPort: 1883
          # En caso de utilizar un configMap con atributos clave valor 
          # Y queremos pasar por variable de entorno los datos:
          env:
            - name: ENV_VARIABLE_NAME # especificamos el nombre de nuestra variable de entorno
              valueFrom: # Especificar de donde tomaremos el valor
                configMapKeyRef: # Tipo de archivo de donde capturaremos el valor, en caso de secret es secretKeyRef
                  name: CONFIG_MAP_NAME # Ponemos el nombre exacto que posee el config map
                  key: CONFIG_MAP_DATA_KEY # Ponemos el nombre de la llave que vamos a utilizar
          volumeMounts: # Para montar los volumenes del pod al contenedor.
            - name: mosquitto-config # nombre del volumen a montar, mismo de abajo
              mountPath: /mosquitto/config # ponemos en que parte del contenedor queremos montar ese archivo
            - name: mosquitto-secret
              mountPath: /mosquitto/secret
              readOnly: true # para evitar que sea modificado por la aplicación
      # Utilizamos volumenes debido a que los configmap y secret que estamos utilizando tienen archivos dentro, o sea dentro del atributo data:
      # secret.file: |
      #     datos....
      volumes: # Para añadir los secrets, podemos utilizar los volumenes
        - name: mosquitto-config # nombre del volumen
          configMap: # Tipo de volumen que vamos a montar
            name: mosquito-config-file # nombre del configmap a utilizar metadata: > name: mosquito-config-file 
        - name: mosquitto-secret
          secret:
            secretName: mosquitto-secret-file
          