apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
--- # Component separation
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes: # Specify the access type for this volume
    - ReadWriteOnce
  resources: # What we are going to ask
    requests: # What we need to work
      storage: 256Mi # Reserve 256 mb from disk to persist data.
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: docker.uclv.cu/mongo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts: # Con este bloque estamos definiendo un volumen interno 
            - name: storage # Nombre del volumen interno del contenedor
              mountPath: /data/db # Path dentro del contenedor para montarlo
      volumes: # Volúmenes que vamos a utilizar
        - name: storage # Tomamos el mismo nombre puesto en volume Mounts
          persistentVolumeClaim: # Decimos que utilizaremos el volumen de persistencia creado anteriormente
            claimName: mongo-pvc # Le ponemos el nombre dado al volumen de persistencia