apiVersion: v1
kind: Service
metadata:
  name: springService
spec:
  selector:
    app: springApp
  type: NodePort
  ports:
    - protocol: TCP
      port: 9878
      targetPort: 9887
      name: TCP-port
      nodePort: 8988 # Puerto para que las otras aplicaciones del cluster accedan a el